[tool.poetry]
name = "minesweeper"
version = "0.1.0"
description = "Cross-platform terminal based minesweeper."
authors = ["Chase Sterling <chase.sterling@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
asciimatics = "^1.11.0"
click = "^7.0"
z3-solver = {version = "^4.8.7", optional = true}

[tool.poetry.extras]
noguess = ["z3-solver"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
